import assert from "node:assert/strict";
import test from "node:test";
import { evaluateFeBValidity } from "./feBQualificationEngine.ts";
import { createEmptyQualificationProfile, createQualificationEvent } from "./pilotQualifications.ts";

const profile = { ...createEmptyQualificationProfile(), configured: true, feBEnabled: true };
let seq = 0;
function event(type, dateIso, extra = {}) { seq += 1; return createQualificationEvent({ type, dateIso, source: "MANUAL", ...extra }, { uuid: () => `123e4567-e89b-42d3-a456-${String(seq).padStart(12, "0")}`, now: () => new Date("2026-09-07T00:00:00Z") }); }
const cert = (issue = "2022-01-01", expiry = "2027-01-01") => event("FE_B_CERTIFICATE", issue, { expiryDateIso: expiry });
const refresher = (date = "2025-01-01", extra = {}) => event("FE_B_REFRESHER_COURSE", date, extra);
const assessment = (date = "2025-01-01", kind = "SKILL_TEST", extra = {}) => event("FE_B_SUPERVISED_ASSESSMENT", date, { assessmentKind: kind, examiner: { name: "Inspecteur" }, ...extra });
const evaluate = (events, referenceDateIso = "2026-09-07", extra = {}) => evaluateFeBValidity({ profile, events, ascensions: [], referenceDateIso, ...extra });

test("FE(B) désactivé et certificat absent", () => { assert.equal(evaluateFeBValidity({ profile: { ...profile, feBEnabled: false }, events: [], ascensions: [], referenceDateIso: "2026-09-07" }).status, "NOT_APPLICABLE"); assert.equal(evaluate([]).status, "UNKNOWN"); });
test("validité administrative inclut l'échéance et expire le lendemain", () => { assert.equal(evaluate([cert()], "2027-01-01").certificateStatus, "COMPLIANT"); const expired = evaluate([cert()], "2027-01-02"); assert.equal(expired.status, "EXPIRED"); assert.equal(expired.renewalRequired, true); });
test("l'expiration explicite reste la source de vérité", () => { const result = evaluate([cert("2022-01-01", "2026-10-15")]); assert.equal(result.expiryDateIso, "2026-10-15"); assert.equal(result.certificateStatus, "COMPLIANT"); });
test("refresher seulement pendant la validité", () => { assert.equal(evaluate([cert(), refresher("2022-01-01")]).refresherStatus, "COMPLIANT"); assert.equal(evaluate([cert(), refresher("2021-12-31")]).refresherStatus, "ACTION_REQUIRED"); assert.equal(evaluate([cert(), refresher("2027-01-02")]).refresherStatus, "ACTION_REQUIRED"); });
test("OTHER_TRAINING et FI_B_REFRESHER_TRAINING sont exclus", () => assert.equal(evaluate([cert(), event("OTHER_TRAINING", "2025-01-01"), event("FI_B_REFRESHER_TRAINING", "2025-01-01")]).refresherStatus, "ACTION_REQUIRED"));
test("les trois natures d'acte supervisé sont admissibles", () => { for (const kind of ["SKILL_TEST", "PROFICIENCY_CHECK", "ASSESSMENT_OF_COMPETENCE"]) assert.equal(evaluate([cert(), assessment("2025-01-01", kind)]).supervisedAssessmentStatus, "COMPLIANT"); });
test("fenêtre supervisée ancrée sur expiry avec bornes inclusives", () => { assert.equal(evaluate([cert(), assessment("2025-01-01")]).supervisedAssessmentStatus, "COMPLIANT"); assert.equal(evaluate([cert(), assessment("2024-12-31")]).supervisedAssessmentStatus, "ACTION_REQUIRED"); assert.equal(evaluate([cert(), assessment("2027-01-01")]).supervisedAssessmentStatus, "COMPLIANT"); assert.equal(evaluate([cert(), assessment("2027-01-02")]).supervisedAssessmentStatus, "ACTION_REQUIRED"); });
test("regulatoryRole FE_B et supervisedByFiB seuls ne prouvent rien", () => { const a = { id: "a", sourceFlightId: null, source: "MANUAL", dateIso: "2025-01-01", date: "", balloonModel: "Z", registration: "F-X", departure: "A", arrival: "B", category: "Libre à air chaud", pilotFunction: "Pilote", regulatoryRole: "FE_B", supervisedByFiB: true, nightFlight: false, maximumAltitudeM: null, gpsDurationMinutes: null, officialDurationMinutes: 60, observations: "" }; assert.equal(evaluateFeBValidity({ profile, events: [cert()], ascensions: [a], referenceDateIso: "2026-09-07" }).supervisedAssessmentStatus, "ACTION_REQUIRED"); });
test("preuve liée supprimée ou sans ascension ne crédite pas", () => { const deleted = assessment("2025-01-01", "SKILL_TEST", { officialAscensionId: "gone", officialAscensionDeletedAt: "2026-01-01T00:00:00Z" }); const missing = assessment("2025-01-02", "SKILL_TEST", { officialAscensionId: "missing" }); assert.equal(evaluate([cert(), deleted, missing]).supervisedAssessmentStatus, "ACTION_REQUIRED"); });
test("le certificat récent définit le cycle et exclut les anciennes preuves", () => { const old = cert("2017-01-01", "2022-01-01"), current = cert("2022-02-01", "2027-02-01"); const result = evaluate([old, refresher("2021-01-01"), assessment("2021-01-01"), current]); assert.equal(result.certificateEventId, current.id); assert.equal(result.refresherStatus, "ACTION_REQUIRED"); assert.equal(result.supervisedAssessmentStatus, "ACTION_REQUIRED"); });
test("toutes les preuves donnent VALID et une preuve certaine manquante ACTION_REQUIRED", () => { assert.equal(evaluate([cert(), refresher(), assessment()]).status, "VALID"); assert.equal(evaluate([cert(), refresher()]).status, "ACTION_REQUIRED"); });
test("un acte incomplet donne UNKNOWN quand il empêche seul la conclusion", () => { const incomplete = event("FE_B_SUPERVISED_ASSESSMENT", "2025-01-01", { examiner: { name: "Inspecteur" } }); assert.equal(evaluate([cert(), refresher(), incomplete]).status, "UNKNOWN"); });
