import assert from "node:assert/strict";
import test from "node:test";
import { evaluateFiBRecency } from "./fiBQualificationEngine.ts";
import { createEmptyQualificationProfile, createQualificationEvent } from "./pilotQualifications.ts";

const referenceDateIso = "2026-09-05";
const baseProfile = { ...createEmptyQualificationProfile(), configured: true, fiBEnabled: true, historyCoverageStartDate: "2017-09-05" };
let seq = 0;
function ascension(id, dateIso, minutes, extra = {}) { return { id, sourceFlightId: null, source: "MANUAL", dateIso, date: dateIso, balloonModel: "Z", registration: "F-TEST", departure: "A", arrival: "B", category: "Libre à air chaud", pilotFunction: "Pilote", regulatoryRole: "FI_B", supervisedByFiB: false, nightFlight: false, maximumAltitudeM: null, gpsDurationMinutes: null, officialDurationMinutes: minutes, observations: "", ...extra }; }
function event(type, dateIso, extra = {}) { seq += 1; return createQualificationEvent({ type, dateIso, source: "MANUAL", ...extra }, { uuid: () => `123e4567-e89b-42d3-a456-${String(seq).padStart(12, "0")}`, now: () => new Date("2026-09-05T00:00:00Z") }); }
function evaluate({ profile = baseProfile, events = [], ascensions = [], coverage } = {}) { return evaluateFiBRecency({ profile, events, ascensions, referenceDateIso, ...(coverage !== undefined ? { historyCoverageStartDate: coverage } : {}) }); }

test("FI(B) désactivé est non applicable", () => assert.equal(evaluate({ profile: { ...baseProfile, fiBEnabled: false } }).status, "NON_APPLICABLE"));
test("359 min sont insuffisantes et 360 min satisfont l'exigence", () => { assert.equal(evaluate({ ascensions: [ascension("a", "2026-01-01", 359)] }).instructionRequirementStatus.status, "ACTION_REQUIRED"); assert.equal(evaluate({ ascensions: [ascension("a", "2026-01-01", 360)] }).instructionRequirementStatus.status, "COMPLIANT"); });
test("PIC et DUAL sont exclus", () => assert.equal(evaluate({ ascensions: [ascension("p", "2026-01-01", 300, { regulatoryRole: "PIC" }), ascension("d", "2026-01-02", 300, { regulatoryRole: "DUAL" })] }).instructionMinutes36m, 0));
test("FE(B) skill test et proficiency checks prouvés sont crédités", () => { const ascensions = [ascension("s", "2026-01-01", 120, { regulatoryRole: "FE_B", flightNature: "SKILL_TEST" }), ascension("p", "2026-01-02", 120, { regulatoryRole: "FE_B", flightNature: "PROFICIENCY_CHECK_BPL" }), ascension("c", "2026-01-03", 120, { regulatoryRole: "FE_B", flightNature: "COMMERCIAL_PROFICIENCY_CHECK" })]; assert.equal(evaluate({ ascensions }).instructionMinutes36m, 360); });
test("FE(B) ordinaire est exclu", () => assert.equal(evaluate({ ascensions: [ascension("fe", "2026-01-01", 500, { regulatoryRole: "FE_B", flightNature: "STANDARD" })] }).instructionMinutes36m, 0));
test("AoC lié crédite une fois l'ascension FE(B)", () => { const a = ascension("aoc", "2026-01-01", 360, { regulatoryRole: "FE_B", flightNature: "SKILL_TEST" }); const e = event("FI_B_ASSESSMENT_OF_COMPETENCE", "2026-01-01", { officialAscensionId: "aoc" }); const result = evaluate({ ascensions: [a], events: [e] }); assert.equal(result.instructionMinutes36m, 360); assert.deepEqual(result.sourceAscensionIds, ["aoc"]); });
test("refresher strict, frontière incluse et types génériques exclus", () => { assert.equal(evaluate({ events: [event("FI_B_REFRESHER_TRAINING", "2023-09-05")] }).refresherRequirementStatus.status, "COMPLIANT"); assert.equal(evaluate({ events: [event("FI_B_REFRESHER_TRAINING", "2023-09-04")] }).refresherRequirementStatus.status, "ACTION_REQUIRED"); assert.equal(evaluate({ events: [event("OTHER_TRAINING", "2026-01-01"), event("TRAINING_FLIGHT_BPL", "2026-01-01")] }).refresherRequirementStatus.status, "ACTION_REQUIRED"); });
test("supervision strictement dédiée avec frontière 108 mois incluse", () => { assert.equal(evaluate({ events: [event("FI_B_SUPERVISED_INSTRUCTION", "2017-09-05")] }).supervisedInstructionRequirementStatus.status, "COMPLIANT"); assert.equal(evaluate({ events: [event("FI_B_SUPERVISED_INSTRUCTION", "2017-09-04")] }).supervisedInstructionRequirementStatus.status, "ACTION_REQUIRED"); assert.equal(evaluate({ ascensions: [ascension("pic", "2026-01-01", 360, { regulatoryRole: "PIC", supervisedByFiB: true })] }).supervisedInstructionRequirementStatus.status, "ACTION_REQUIRED"); });
test("événement lié à une ascension supprimée ou absente ne crédite pas", () => { const deleted = event("FI_B_SUPERVISED_INSTRUCTION", "2026-01-01", { officialAscensionId: "gone", officialAscensionDeletedAt: "2026-02-01T00:00:00Z" }); assert.equal(evaluate({ events: [deleted] }).supervisedInstructionRequirementStatus.status, "ACTION_REQUIRED"); const missing = event("FI_B_SUPERVISED_INSTRUCTION", "2026-01-01", { officialAscensionId: "missing" }); assert.equal(evaluate({ events: [missing] }).supervisedInstructionRequirementStatus.status, "ACTION_REQUIRED"); });
test("legacy UNKNOWN est borné par son potentiel", () => { const legacy = ascension("legacy", "2026-01-01", 120, { regulatoryRole: null }); assert.equal(evaluate({ ascensions: [ascension("fi", "2026-01-01", 300), legacy], coverage: "2025-01-01" }).instructionRequirementStatus.status, "UNKNOWN"); assert.equal(evaluate({ ascensions: [ascension("fi", "2026-01-01", 200), legacy], coverage: "2025-01-01" }).instructionRequirementStatus.status, "ACTION_REQUIRED"); assert.equal(evaluate({ ascensions: [ascension("fi", "2026-01-01", 360), legacy], coverage: "2025-01-01" }).instructionRequirementStatus.status, "COMPLIANT"); });
test("les trois exigences donnent À jour, une absence certaine Action requise", () => { const events = [event("FI_B_REFRESHER_TRAINING", "2026-01-01"), event("FI_B_SUPERVISED_INSTRUCTION", "2026-01-01")]; assert.equal(evaluate({ events, ascensions: [ascension("fi", "2026-01-01", 360)] }).status, "COMPLIANT"); assert.equal(evaluate({ events: events.slice(0, 1), ascensions: [ascension("fi", "2026-01-01", 360)] }).status, "ACTION_REQUIRED"); });
