"use client";
import { ChevronLeft, ExternalLink, Pencil, Share2, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { balloonDocumentStorage } from "../../../../../../lib/balloonDocumentStorage";
import { BALLOON_DOCUMENT_ACCEPT, balloonDocumentCategoryLabel, canShareBalloonDocument, replaceDocumentObjectUrl, revokeDocumentObjectUrl, validateBalloonDocumentFile, type BalloonDocument } from "../../../../../../lib/balloonDocuments";
import styles from "../../../../../More.module.css";

function fileSize(size: number): string { return size < 1_048_576 ? `${Math.max(1, Math.round(size / 1024))} Ko` : `${(size / 1_048_576).toLocaleString("fr-FR", { maximumFractionDigits: 1 })} Mo`; }

export default function BalloonDocumentPage() {
  const { id, documentId } = useParams<{ id: string; documentId: string }>(); const balloonId = decodeURIComponent(id); const decodedDocumentId = decodeURIComponent(documentId); const router = useRouter();
  const [document, setDocument] = useState<BalloonDocument | null>(null); const [file, setFile] = useState<Blob | null>(null); const [objectUrl, setObjectUrl] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const replaceInput = useRef<HTMLInputElement>(null); const objectUrlRef = useRef<string | null>(null);
  useEffect(() => { let active = true; void Promise.all([balloonDocumentStorage.getDocument(decodedDocumentId), balloonDocumentStorage.getDocumentFile(decodedDocumentId)]).then(([metadata, storedFile]) => { if (!active) return; if (!metadata || metadata.balloonId !== balloonId) { setError("Document introuvable."); return; } setDocument(metadata); if (!storedFile) { setError("Document indisponible. Remplacez le fichier ou supprimez cette référence."); return; } const url = replaceDocumentObjectUrl(objectUrlRef.current, storedFile); objectUrlRef.current = url; setObjectUrl(url); setFile(storedFile); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Document introuvable."); }); return () => { active = false; revokeDocumentObjectUrl(objectUrlRef.current); objectUrlRef.current = null; }; }, [balloonId, decodedDocumentId]);
  const rename = async () => { if (!document) return; const title = window.prompt("Renommer le document", document.title); if (!title?.trim() || title.trim() === document.title) return; try { setDocument(await balloonDocumentStorage.updateDocument(document.id, { title })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Le document n’a pas pu être renommé."); } };
  const replace = async (replacement: File | undefined) => { if (!document || !replacement) return; const issue = validateBalloonDocumentFile(replacement); if (issue) { setError(issue); return; } try { const updated = await balloonDocumentStorage.replaceDocumentFile(document.id, replacement); const url = replaceDocumentObjectUrl(objectUrlRef.current, replacement); objectUrlRef.current = url; setObjectUrl(url); setDocument(updated); setFile(replacement); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Le fichier n’a pas pu être remplacé."); } };
  const share = async () => { if (!document || !file) return; const sharedFile = new File([file], document.originalFileName, { type: document.mimeType }); const data = { title: document.title, files: [sharedFile] }; if (!canShareBalloonDocument(navigator, data)) { setError("Le partage de fichiers n’est pas disponible sur cet appareil."); return; } try { await navigator.share(data); setError(null); } catch (reason) { if (reason instanceof DOMException && reason.name === "AbortError") return; setError("Le partage de fichiers n’est pas disponible sur cet appareil."); } };
  const remove = async () => { if (!document || !window.confirm(`Supprimer ce document ?\n\n« ${document.title} » sera retiré du dossier du ballon.`)) return; try { await balloonDocumentStorage.deleteDocument(document.id); router.push(`/more/profile/balloons/${encodeURIComponent(balloonId)}/documents`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Le document n’a pas pu être supprimé."); } };
  return <main className={styles.screen}><div className={styles.layout}><Link href={`/more/profile/balloons/${encodeURIComponent(balloonId)}/documents`} className={styles.back}><ChevronLeft size={18} /> Documents</Link>{error && !document ? <p className={styles.error}>{error}</p> : document && <><header><p className={styles.eyebrow}>{balloonDocumentCategoryLabel(document.category)}</p><h1 className={styles.title}>{document.title}</h1><p className={styles.subtitle}>{document.originalFileName} · {fileSize(document.sizeBytes)} · ajouté le {new Date(document.createdAt).toLocaleDateString("fr-FR")}</p></header>
    {objectUrl && <section className={styles.documentPreview}><object data={objectUrl} type={document.mimeType} aria-label={document.title}><p>Ce document ne peut pas être prévisualisé ici.</p></object></section>}
    {objectUrl && <a href={objectUrl} target="_blank" rel="noreferrer" className={styles.documentPrimaryAction}><ExternalLink size={18} /> Ouvrir le document</a>}
    <div className={styles.documentActions}><button type="button" onClick={() => void rename()}><Pencil size={17} /> Renommer</button><button type="button" onClick={() => replaceInput.current?.click()}><Upload size={17} /> Remplacer</button><button type="button" onClick={() => void share()}><Share2 size={17} /> Partager</button><button type="button" className={styles.dangerAction} onClick={() => void remove()}><Trash2 size={17} /> Supprimer</button></div>
    <input ref={replaceInput} hidden type="file" accept={BALLOON_DOCUMENT_ACCEPT} onChange={(event) => void replace(event.target.files?.[0])} />{error && <p className={styles.error}>{error}</p>}</>}
  </div></main>;
}
